### ISSUE TITLE
Make zipkin and lightstep optional based on bazel --define

### ISSUE THREAD

**Issue by tschroed** [lyft/envoy#1006]
Following PR #994 make it possible to --define lightstep_tracing=disabled and zipkin_tracing=disabled so that they're not linked into the Envoy binary. PR #982 was doing this, but the build dependencies are slightly restructured and the ifdefs are no longer necessary.

@mrice32

**Comment by mrice32** [comment]
Sounds good.  I'll look into #982 to figure out how to add this on top.

**Comment by htuch** [comment]
I'm wondering if we want to go down the path of `--define` or we want to just make it easy to declare build targets that take the core Envoy (without any filters) and then link in the filters/tracers that are actually wanted? We could define libraries of common filters. #994 makes the second option more plausible, since there are no longer any deep dependency relationships and all filters/tracers can be combined in the final build target.

**Comment by tschroed** [comment]
I think the combinatorial explosion becomes problematic when we have lightstep, zipkin, and dapper for monitoring. Text, proto, and Cloud Logging. Statsd and Stackdriver for monitoring.

Certainly anyone who wants to could mix and match and maintain their own build targets, but at that point it's not really any different than just having a build config that supplies some --defines.

That said, I don't feel especially strongly. For my own selfish needs we'll need our own BUILD to link in Google-specific stuff anyhow and maybe that's how others will end up doing it for similar reasons.

**Comment by htuch** [comment]
Since we're the main folks who have this requirement today and have a good solution that will also generalize to other site specific Bazel builds I'm going to close this one out. Please reopen if this is needed in the future for any reason.
