### ISSUE TITLE
bad performance during load test

### ISSUE THREAD

**Issue by aguilbau** [lyft/envoy#1033]
Hello,

When doing load testing, I find some odd behaviour : 
the first 30 secondes of testing will have very bad results.

Here is a graph of the latencies on an aws m4.xlarge instance, sending 400 req/s.
http://i.imgur.com/E0t4CcF.png

**Comment by mattklein123** [comment]
Hi @aguilbau. I'm sorry but there isn't enough actionable info in this report to help out. In general, I'm very skeptical that Envoy itself is the issue here given its architecture. We would need to do more debugging to see where the time is being spent. Envoy stats may help. 

I'm going to close this issue. Feel free to reopen if you can provide more info that implicates a particular problem. We will of course also be tracking warm up perf when we start working on our perf framework per @htuch.

**Comment by ddragosd** [comment]
are there any official performance tests posted somewhere along with their results ? I'd be interested to see them, if any.

**Comment by mattklein123** [comment]
> are there any official performance tests posted somewhere along with their results

No, there is nothing officially published currently. Maintaining and publishing reliable perf results takes a considerable amount of effort which historically we have not had resources for. However we do have some work going on at Google on performance profiling which should result in repeatable and publishable numbers. ETA couple of months most likely. cc @htuch
