### ISSUE TITLE
ci: reduce disk space

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#1400]
I'm not sure that we can start with more disk space than we do now. It looks like we have about 20GB  free when the build starts. It seems like ASAN is starting to get very close to limit.

@htuch @dnoe what absurd hacks can we do here? Delete test binaries after test runs? Split into 2 CI runs?

**Comment by mattklein123** [comment]
P.S. I think the chance of getting more disk space on Travis is zero. That's not an option.

**Comment by PiotrSikora** [comment]
ASAN tests are failing already... :(

`/usr/bin/ld.gold: fatal error: bazel-out/local-dbg/bin/external/envoy/test/server/http/admin_test: No space left on device`

**Comment by htuch** [comment]
Here are some other/modified ideas to the above to work around this limit:

1. Dynamically link tests. We would need to modify the build of external deps to support this, plus there were some issues that came up when we used to do this in the early days of Bazel that I've since forgotten. Could be worth exploring again. This would also make the developer UX and Travis build times faster.

2. Run the single fat test binary that we use for coverage for ASAN (and other problematic builds).

3. Have `test/main.cc` perform a `::unlink(argv[0]);` to cleanup after itself. This does evil things to the Bazel cache, but there may be some way to get this to work for the purpose of ephemeral Travis CI runs that always start clean.

I'd +1 the sentiment that we're starting to hit the point that we're throwing good engineering time after bad, when you combine the time spent looking into issues around both CPU and disk space usage on Travis. I know the plan is to get off Travis by EOY, could be worth trying to accelerate this.

**Comment by htuch** [comment]
BTW, if you want confirmation that it's the O(100) static binaries that are to blame for disk use, you can do `./ci/run_envoy_docker.sh 'rm -rf /build/tmp; ./ci/do_ci.sh bazel.asan; du -ka /build/tmp | sort -n` and see results like:

```
262848  ./_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy/bazel-out/local-dbg/bin/external/envoy/test/integration/http2_integration_test
263144  ./_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy/bazel-out/local-dbg/bin/external/envoy/test/integration/http2_upstream_integration_test
263196  ./_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy/bazel-out/local-dbg/bin/external/envoy/test/integration/tcp_proxy_integration_test
264648  ./_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy/bazel-out/local-dbg/bin/external/envoy/test/integration/grpc_json_transcoder_integration_test
```
