### ISSUE TITLE
How many clusters has envoy been tested to support?

### ISSUE THREAD

**Issue by shalako** [lyft/envoy#1445]
Our target for an edge southbound router is 200,000 backend clusters. Has it been tested at this scale? 

Is CPU and as a result, throughput/latency, impacted as a result of processing frequent changes to this many clusters?

Envoy emits many wonderful statistics per cluster. Are these statistics batched in any way, or are counters emitted per request?

**Comment by mattklein123** [comment]
These questions might be better for envoy-users@, but will try to answer here:

> Our target for an edge southbound router is 200,000 backend clusters. Has it been tested at this scale?

No, almost definitely not.

> Is CPU and as a result, throughput/latency, impacted as a result of processing frequent changes to this many clusters?

Yes. In general, the more clusters you have the more memory you will need to hold the data. The number of clusters itself is not really relevant, all of the processing should generally be O(1) for lookup. However, depending on what type of service discovery you are using, all of the update polling will take CPU. At 200,000 clusters I would imagine it will be problematic but I don't know. The v2 API with bidi gRPC streaming and ADS would help here, since you could probably have a single stream and just send down EDS updates as a single cluster changes. This is probably your best bet but this code isn't ready yet. @htuch is working on it.

> Envoy emits many wonderful statistics per cluster. Are these statistics batched in any way, or are counters emitted per request?

Counters/Gauges are latched and flushed. Timers are not. By default though 200,000 is going to be a huge amount of stats. Some optimization might be needed here. By default you won't be able to use hot restart as the # of stats will be bigger than the default shared memory region. You can either disable hot restart at compile time, or work on a patch to make the size of the shared memory region configurable at compile or start time.

**Comment by shalako** [comment]
Thank you for the reply. I will look for the users list. 

Is there a Slack channel?

**Comment by mattklein123** [comment]
The communication options are listed on the project readme.

**Comment by dnoe** [comment]
At the moment we congregate in the Gitter chat at
https://gitter.im/lyft/envoy

Slack channel will replace this Real Soon Now.

**Comment by mattklein123** [comment]
Closing this for now. Can reopen and/or use email if there are more questions.
