### ISSUE TITLE
Per-request timing information

### ISSUE THREAD

**Issue by mrice32** [lyft/envoy#1464]
We are interested in logging granular HTTP timing info on a per-request basis (non-aggregated) to a custom log destination along with other request-specific metadata.  We are currently planning on measuring this through a custom filter and logging on destruction.  However, it may be desirable to perform these measurements in a general way in the open source and make them available for consumption by HTTP filters and access logs (maybe through the RequestInfo object).  The durations that we are interested in are all timed from the request start to particular request events:
- entire request sent to upstream
- entire response received from upstream
- response received by the downstream client (acked)

Is there an appetite for this sort of per-request timing information to be included and accessible in Envoy?

cc @htuch

**Comment by mattklein123** [comment]
In general I think this would be useful for general open source. Also, depending on what precise definitions you want for these timings, it's not going to be possible to do in a filter. Specifically, filters are not always aware of lack of window updates and/or TCP level pauses that cause buffering.

For the three timings that you have above, can you spell out a bit more how you plan on timing them (setting aside how Envoy works for a second). Also, we already have x-envoy-upstream-time headers and startTime() in RequestInfo (which when access logs are written gives you total end to end to end time, minus end of response stream buffering and TCP buffering).

**Comment by mrice32** [comment]
Great!  Agreed. The filter implementation would've been a pretty inaccurate approach. Here are the definitions we would like to use (please forgive me if I butcher any terminology/concepts here) and my understanding of when the timestamps would be captured:
- request sent to upstream - stamped just after the last byte of the request is passed to the kernel's send TCP buffer.
- response received from upstream - stamped just after the last byte of the request is read by Envoy from the receive TCP buffer.
- response sent to downstream client (updated from above) - I think it makes sense to stamp just after the last response byte is written to the send TCP buffer going to the downstream client rather than trying to get the time when the last ack comes back, which requires polling the kernel.

I've looked into both the x-envoy-upstream-time headers, which will certainly be useful for our timing output.  Currently, we were planning on generating the above durations by differencing their timestamps with the `startTime()` from `RequestInfo`.  IIUC, this `startTime()` is stamped at the time when the first header bytes are received, roughly?  It would be a bit nicer to be able to difference against the time when the TCP handshake has just finished, but I'm not sure if this is easy or possible.

In regards to the current way of doing end-to-end time measurement, I was curious about the time that the `log()` function is actually called on the `AccessLog::Instance` object.  It appears to be called in the [ActiveStream destructor](https://github.com/lyft/envoy/blob/master/source/common/http/conn_manager_impl.cc#L350), but because the `ActiveStream` is destroyed through deferred deletion, doesn't that mean that its destructor will be called at a later point in time, making it a strange point at which to measure the timestamp marking the end of the request?  Is this timing difference negligible?

Please correct me if anything I've mentioned seems fishy or incorrect.

**Comment by mattklein123** [comment]
This is really complicated unfortunately. I will drop some comments in here prior to our meeting later today and then we can update this issue for public visibility of that discussion.

> request sent to upstream - stamped just after the last byte of the request is passed to the kernel's send TCP buffer.

Loosely, we track this today via the `downstream_request_complete_time_` in the router. This forms the start time for the `x-envoy-upstream-time` header. Obviously, this is not accurate, as after the request is fully processes and forwarded, a bunch of things can take further time: HTTP/1.1 connection pool acquisition, tail flow control (meaning, we got past flow control for most of the upload, but there might be flow control that blocks the last bit of the request from going on the wire). In order to make this fully accurate to the TCP level, it will be a tremendous amount of work. Basically, it will involve tracking request data all the way down to the byte level, and firing callbacks when a particular byte location in the output byte stream actually gets written. This is technically possible, but it's not clear to me that the better fidelity is worth it in the comment case (especially because we have stats on the # of flow control events).

> response received from upstream - stamped just after the last byte of the request is read by Envoy from the receive TCP buffer.

This is effectively the `x-envoy-upstream-time` header. There is no real flow control on the receive path, so when the last byte comes into the TCP buffer modulo some small delta in instructions running, it will fire the event.

> response sent to downstream client (updated from above) - I think it makes sense to stamp just after the last response byte is written to the send TCP buffer going to the downstream client rather than trying to get the time when the last ack comes back, which requires polling the kernel.

Loosely, this is the time that is snapped in the access log today. To get more accuracy, you have all the problems with the first item above. You need per byte tracking and callbacks. Also, if you want to track ACK data, this becomes even more complicated. (As an aside, is this even possible via API? What API? Just curious). Again it's not clear to me that the mountain of work required to make this happen is worth it.

> IIUC, this startTime() is stamped at the time when the first header bytes are received, roughly? It would be a bit nicer to be able to difference against the time when the TCP handshake has just finished, but I'm not sure if this is easy or possible.

This is actually when all header bytes are received. This is at stream level and is somewhat unrelated to TCP handshake complete since for HTTP/2 and HTTP/1 keep alive the TCP handshake will have happened a long time previous. Either way, tracking TCP handshake complete and TLS handshake complete times would not be difficult.

> doesn't that mean that its destructor will be called at a later point in time, making it a strange point at which to measure the timestamp marking the end of the request? Is this timing difference negligible?

IMO the time delta is negligible. It will happen in the next event loop iteration which is going to be in the microsecond granularity level.

cc @alyssawilk

**Comment by alyssawilk** [comment]
" Basically, it will involve tracking request data all the way down to the byte level, and firing callbacks when a particular byte location in the output byte stream actually gets written. This is technically possible, but it's not clear to me that the better fidelity is worth it in the comment case "

If it isn't done now, I believe it will be done in a few years.    These metrics are super useful for low-level latency analysis and crazy follow-up optimizations which some companies (*cough*) care a lot about :-)  So +1 to interest.

Worth noting for HTTP-TCP you can get the last-acked-time fairly easily but for H2 it's virtually impossible.  You can do some clever things with underlying socket rtt measurements and H2 pings to estimate both kernel/network time plus additional buffer bloat - happy to brainstorm options or connect you to the folks who have done this at Google.

**Comment by mattklein123** [comment]
> If it isn't done now, I believe it will be done in a few years. These metrics are super useful for low-level latency analysis and crazy follow-up optimizations which some companies (cough) care a lot about :-) So +1 to interest.

I agree it's interesting and am not opposed to it at all, was just explaining that it will be a huge amount of work. If we want to go down this route we should do a full design doc.

**Comment by mrice32** [comment]
Meeting resolution:
- It is of general interest to add more granular timing info to RequestInfo for consumption by filters and access logs.  We will use Matt's suggested sources to populate the timestamps mentioned above.
- More accurate timing information is a somewhat orthogonal problem to the above.  While there does seem to be long-term interest in getting more accurate timestamps, this doesn't seem to be a high priority.

**Comment by mrice32** [comment]
Closing because this additional info has been added to RequestInfo.
