### ISSUE TITLE
feature request: implement file watching for envoy config and auto restart

### ISSUE THREAD

**Issue by kuroneko25** [lyft/envoy#156]
It would be really helpful if there is an option to tell envoy to watch for config file changes and perform auto-restart upon detecting changes in the config file.

**Comment by mattklein123** [comment]
The main issue here is that Envoy hot restart has been designed such that Envoy cannot restart itself (it required an external process like https://github.com/lyft/envoy/blob/master/restarter/hot-restarter.py) The reason this was done is so that Envoy hot restart can work across containers (Envoy can be hot restarted in a new container alongside an old one which eventually exits).

There is ongoing thought being given to tighter integration with Envoy in k8s and hopefully we can sort this out at the same time.

**Comment by mattklein123** [comment]
I'm going to close this out as won't fix. I don't think Envoy will ever do auto restart for config changes but would require some external process runner to do it.
