### ISSUE TITLE
1.1.0 release tracker

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#243]
We are stabilizing after all of the recent perf changes. Plan on doing a 1.1.0 release in the next 2 weeks. If anyone wants any other small features/fixes to be in the official release please speak up.

**Comment by rshriram** [comment]
TODO:
* add the access logging for fault injection. The one liner patch to emit access log entries [shriram]
* weighted routing for clusters

Wishlist (if possible):
* How easy or hard is it to push the fault injection configuration into per-route filter level instead of having a separate fault block that acts on all routes ?
* Is it possible to refactor the lightstep code such that we have an interface for opentracing (may be not implemented) but its there, for others to add and compile an extended version of Envoy from stable code base (1.1.0) + some implementation of open tracing (seems to be missing now, but hoping it would appear soon)

**Comment by mattklein123** [comment]
> add the access logging for fault injection. The one liner patch to emit access log entries [shriram]

If you want to get this into 1.1.0 please do the patch this week. The rest of them realistically aren't going to happen in time to snap the release. We can get those into 1.2.0.

**Comment by mattklein123** [comment]
released
