### ISSUE TITLE
Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by andrewwebber** [lyft/envoy#311]
Are there any plans to look at a kubernetes ingress controller implementation?

**Comment by mattklein123** [comment]
Please following along with the https://github.com/istio project. They are building k8s support for Envoy (and other service mesh proxies).

**Comment by emmanuel** [comment]
Istio looks interesting, but I don't think that it's particularly relevant to the request. As far as I saw (from a quick look), istio is targeting service-to-service communications (i.e., east-west, service mesh). An ingress controller is about north-south communications. 

Please consider this another expression of interest for an Envoy-based ingress controller. Preferably this would be simple and unencumbered by ambitions of targeting a multitude of use-cases.

**Comment by mattklein123** [comment]
@emmanuel it's very unlikely that we will work on any direct k8s integration any time soon. From my perspective Istio is the vehicle that will get Envoy into k8s including an ingress controller. It's possible this will change in the future depending on project trajectories, but for now I think it's best to let the Istio project evolve and see where it goes.

cc @rshriram @louiscryan in case you want to add any other color here. I'm going to leave this issue open just to track this general question since it keeps coming up.

**Comment by emmanuel** [comment]
@mattklein123 thanks for the response. I fired off that comment without doing my homework on istio and I hope that it didn't come across as uninformed, entitled and/or ubnoxious. That is how my comment looks to me upon re-reading, so I'm asking for a more generous interpretation than I myself would likely give. Hmmm. 

Anyhow, istio is clearly targeting both east-west and north-south use-cases. It was right there to see if I had but read a bit further. I'll track istio and look forward to it's evolution.

**Comment by emmanuel** [comment]
Curses, I forgot the most important part. Sorry for my tone in the first message.

**Comment by rshriram** [comment]
@emmanuel we are writing an ingress controller for Envoy in Istio, with much more functionality than the limitations of existing ingress controller (i.e. expose lots of Envoy features). It's  a work in progress. Please see https://github.com/istio/manager/pull/71
