### ISSUE TITLE
Create an Envoy FAQ

### ISSUE THREAD

**Issue by junr03** [lyft/envoy#568]
With the amount of community interest, and questions we have received it is time to write an FAQ for envoy. The FAQ would include questions about configurations, operational knowledge, etc. Please comment here with topics that you would like to see covered in the FAQ.

**Comment by rshriram** [comment]
I would rather frame this as a curated collection of How To's, instead of FAQ, as FAQs are typically one liner responses. 

Some very basic how-to's below (all of these need example configurations)

1. Circuit breakers/outlier detection, timeouts and retries and health checks showcasing the interplay between these functions.
2. TLS termination and upstream TLS
3. Open tracing and viewing traces in Zipkin (pursuant to @fabolive's PRs)
4. Stats propagation and monitoring via some standard statsd backend
5. TCP proxying
6. Logical/strict DNS cluster for proxying to cloud foundry/external services
7. Traffic splitting between different upstream clusters
8. Rate limiting with Redis backend, and envoy ratelimit service (go backend)
9. Fault injection

**Comment by richarddli** [comment]
I think there's value in both HOWTOs and FAQs. A lot of people we speak with don't understand why you need a L7 proxy and aren't familiar with a service mesh. 

So answering the question of "Why would I want to use Envoy?" in a non-feature-oriented way, e.g., "if you have a network of services, you're going to need observability and resilience, and you want to do this in a way that's transparent-ish to the service author" is a basic question that I think is worth answering somewhere. (Right now, the focus is on features, e.g., gRPC support, HTTP/2, global rate-limiting, etc. -- great for the expert user, not so great for the smart-but-not-expert user.)

**Comment by dnoe** [comment]
I think this is a great idea, a good starting point is just turning the
What is Envoy page (
https://lyft.github.io/envoy/docs/intro/what_is_envoy.html) into a Q&A
style document.  I can take a first crack at that some time today.  Then
users will have questions that aren't in the FAQ and we can add the answers
once we know what new users are curious about.

I did not find any of the YouTube videos of Matt linked from either the
main Envoy page (https://lyft.github.io/envoy/) or the GitHub readme front
page or the docs.  I found Matt's talk informative about the Envoy design
and deployment philosophy when I first started so we might want to pick
Matt's favorite video version of the talk and link it from somewhere.  The
one I watched is "Lyft's Envoy: From Monolith to Service Mesh - Matt Klein,
Lyft <https://www.youtube.com/watch?v=RVZX4CwKhGE>".

**Comment by richarddli** [comment]
Not sure how many people like transcripts, but for that talk, the transcript is also here: https://www.microservices.com/talks/lyfts-envoy-monolith-service-mesh-matt-klein/.

**Comment by mattklein123** [comment]
I will use this issue to start a basic FAQ and "getting help" guide so that we can have something and then go from there.

**Comment by mattklein123** [comment]
Closing this as we already have the FAQ setup. People can add entries as needed.
