### ISSUE TITLE
replace NOT_IMPLEMENTED w/ NOT_REACHED 

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#590]
We now have NOT_REACHED macro. We should grep for NOT_IMPLEMENTED and switch to NOT_REACHED in places where that is applicable.

cc @jamessynge

**Comment by mattklein123** [comment]
@htuch ^ this is another good starter one for your new grad.

**Comment by htuch** [comment]
@hennna

**Comment by hennna** [comment]
Working on it.
Grep return 17 instances of "NOT_IMPLEMENTED" and 1 instance of "not implemented"

**Comment by htuch** [comment]
FYI, https://github.com/lyft/envoy/blob/master/source/server/config/network/http_connection_manager.cc#L168 is an example of one that should be NOT_REACHED() (since the switch cases cover all possibiilties) and https://github.com/lyft/envoy/blob/1d5035fd0b7bc8e721d059720736a31eb005e329/source/common/http/http2/codec_impl.cc#L350 is a genuine NOT_IMPLEMENTED() (since it's flagging something that is genuinely not implemented today).
