### ISSUE TITLE
Deadlock detection

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#614]
Add support to heartbeat worker threads and a watchdog thread to kill the Envoy process if any threads don't check in for some fixed timeout. This will allows us to catch deadlocks/livelock etc.

Might want to use explicit timers (rather than hearbeating during the event loop), given the way libevent is used today, where we delegate the entire event loop to libevent.

**Comment by mattklein123** [comment]
We already have the per worker watchdog timers, so we could start there, then eventually move to explicit timers via signal.

**Comment by dnoe** [comment]
I will work on this.

**Comment by mattklein123** [comment]
@dnoe potentially obvious, but please make the deadlock detector optional via config. Also, while you are doing this, we might want to make the current watchdog timer intervals configurable ("miss" and "mega miss").

**Comment by htuch** [comment]
Yeah, since the per-watchdog timers may never fire if the event loop is disrupted we should probably move this to its own thread.

**Comment by mattklein123** [comment]
Yup definitely it's own thread, I just meant that the per thread check-ins could happen initially via the watchdog timer code that exists.

**Comment by dnoe** [comment]
Thanks! Agree that there is some stuff to build on in the existing watchdog timer code.  I'll make the current timer intervals configurable and add a new option to control whether deadlock detection is enabled.

**Comment by dnoe** [comment]
As far as configuration here is what I'm implementing:

watchdog_miss_timeout: default 100ms, increments miss counter.
watchdog_megamiss_timeout: default 1s, increments megamiss counter.
watchdog_kill_timeout: default ?, kills process if one thread is stuck this long
watchdog_multi_kill_timeout: default ?, kills process if more than one thread is stuck this long (intended to be a lower threshold than the single kill threshold since it implies a real deadlock vs starvation)

By setting the kill timeouts to 0 that behavior will be inhibited.  I don't see any particular reason to inhibit the stats collection only.

**Comment by mattklein123** [comment]
Fixed by https://github.com/lyft/envoy/pull/655
