### ISSUE TITLE
Support HTTP2 REFUSED_STREAM to allow for retry of non-idempotent requests

### ISSUE THREAD

**Issue by louiscryan** [lyft/envoy#68]
REFUSED_STREAM indicates that the request was not processed by the application layer which should allow requests to be retried elsewhere without violating expectations when idempotency is not known

Supporting this feature only makes sense in client-side and middle proxy scenarios.

**Comment by mattklein123** [comment]
Right now we only have a retry

**Comment by louiscryan** [comment]
All 5xx seems a little dangerous? Internal Server Error & Gateway Timeout leave plenty of scope for the call to have had some effect on state.

**Comment by mattklein123** [comment]
We don't do any retries by default (mainly because of idempotency concerns per your point). The retry policies are configurable on a per route and per request basis. See here:
https://lyft.github.io/envoy/docs/configuration/http_filters/router_filter.html#x-envoy-retry-on
https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route.html#config-http-conn-man-route-table-route-retry

We do have many people who want the "5xx" policy since they know that the calls they are making are idempotent. At Lyft we also use the "connect-failure" policy almost everywhere since that is guaranteed to be idempotent. 

It is very easy to add a new policy and we can definitely add one for a REFUSED_STREAM reset.

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/pull/74
