### ISSUE TITLE
unable to initialize hot restart: unable to bind domain socket with id=0

### ISSUE THREAD

**Issue by fabware** [lyft/envoy#88]
I'm  trying to run two envoy instance on same host and I get error message:  "unable to initialize hot restart: unable to bind domain socket with id=0"

Is it by design or anything I'm missing?

**Comment by mattklein123** [comment]
In general we don't recommend running more than 1 envoy per machine (easier to operate, one source of stats, etc.) but if you want to you can use this option: https://lyft.github.io/envoy/docs/operations/cli.html#cmdoption--base-id

This will tell Envoy to use a different set of unix domain sockets so that each envoy can be hot restarted independently.

**Comment by fabware** [comment]
--base-id 1 solved my problem, thanks for your help and suggestion. 

I would be nice to add the above suggestion along with error message, this may make it easy for  new comers.

**Comment by mattklein123** [comment]
Good idea will reopen to track

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/pull/289

**Comment by mattklein123** [comment]
fixed

**Comment by tlhunter** [comment]
Docs moved to https://www.envoyproxy.io/envoy/operations/cli.html?highlight=base%20id#cmdoption-base-id

**Comment by pcn** [comment]
And https://www.envoyproxy.io/docs/envoy/v1.5.0/operations/cli#cmdoption-base-id
